# Generated by Django 5.2 on 2025-04-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0006_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Insurance',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
