# Generated by Django 5.2 on 2025-04-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0013_bankcard_user_transaction_from_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
